### ISSUE TITLE
Dot leaders in Manual ToC?

### ISSUE THREAD

**Issue by dajare** [sile-typesetter/sile-typesetter.github.io#14] opened 2020-05-26 12:05 UTC
I was just on one of my periodic visits to the SILE website, and was looking again at the manual. It struck me as odd that the ToC dot leaders aren't right-justified, and are even somewhat ragged when you would expect some consistency:

<img width="407" alt="__0-0a-sileman" src="https://user-images.githubusercontent.com/40625/82898399-2d560180-9f51-11ea-8f80-ffe03edae373.png">

Is that by design? It strikes me as aesthetically a bit odd, and especially curious for an potential "shop-window" for a typesetting program!

Anyway, thought I'd mention it, FWIW. (And hi, @alerque!)

**Comment by alerque** [comment] 2020-05-26 12:15
No, that is not by design!

~~We~~ I blew up something and haven't fixed it yet. There was a major overhaul to the length/measurement/unit math such that we're now always passing around smart objects that have units and functions explaining how they relate to other measurements even with dis-similar units (you can multiply `2em * 2` or subtract `1em - 1ex`) and they will know when they are incompatible (you cannot multiply `10%pw * 3en`). The result is a more flexible and predictable system, but it revealed a lot of underlying bugs where various integers were being passed around and it was assumed that they were points when they were actually ratios or ratios when they were penalties or whatever. We haven't weeded out all the cases yet. This is actually a duplicate of SILE [issue #859](https://github.com/sile-typesetter/sile/issues/859). Thanks for reporting it though! And hi back at you!

**Closed as completed by alerque** 2020-05-26 12:15 UTC

**Comment by dajare** [comment] 2020-05-26 12:58
Ah! I did have a look, but guessed wrong about where to put the, ahhh, observation! Hope it's all good where you are.
