### ISSUE TITLE
PDF examples give 404

### ISSUE THREAD

**Issue by astrojuanlu** [sile-typesetter/sile-typesetter.github.io#18] opened 2021-09-06 09:11 UTC
These two links from https://sile-typesetter.org/examples/:

- https://raw.githubusercontent.com/sile-typesetter/sile/master/examples/simple.pdf
- https://raw.githubusercontent.com/sile-typesetter/sile/master/examples/book.pdf

I suppose they were dropped in e74f72326b917b88a301f844670cc47f7f7cb3ba, a year ago.

**Comment by alerque** [comment] 2021-09-06 09:22
Thanks for the report. This appears to be a duplicate of #17. The site examples section really needs some love, SILE has moved well beyond what is in the examples and the site shouldn't be linking into the SILE code repository like that.

**Closed as completed by alerque** 2021-09-06 09:22 UTC
Labels: duplicate
